version: "3.7"
services:
  api:
    image: andrzejd/glog
    ports:
      - 80:80
    depends_on:
      - database
    restart: on-failure:5
  database:
    image: mysql
    volumes:
      - ./storage/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
